name: Generate Snake

on:
workflow_dispatch:

schedule:
- cron: "0 0 * * *"

jobs:
generate:
runs-on: ubuntu-latest

```
permissions:
  contents: write

steps:
  - name: Generate Snake
    uses: Platane/snk@v3
    with:
      github_user_name: mhmadrezapahlevi
      github_token: ${{ secrets.GITHUB_TOKEN }}
      outputs: |
        dist/github-snake.svg
        dist/github-snake-dark.svg?palette=github-dark

  - name: Deploy
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_branch: output
      publish_dir: ./dist
```
